### ISSUE TITLE
Devirt isn't decompiling form correctly

### ISSUE THREAD

**Issue by pliczcoderce** [Washi1337/OldRod#21]
Is decompiling and using one 1 variable by method...

**Comment by Washi1337** [comment]
Please answer the questions as stated by the bug report template. I cannot fix anything if you don't provide me with any information.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior (preferably including a download link to a sample binary).

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by Washi1337** [comment]
I still have no way to reproduce the bug you found.

**Comment by Washi1337** [comment]
Due to the lack of response, I will close this.
